---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: redis-slave
  namespace: redis-slave
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - redis-slave-app
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
