---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: redis-master
  namespace: guestbook
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - redis-master-app
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
