
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: redis-master-pr
  namespace: guestbook
  labels:
    app: redis-master-app
spec:
  clusterReplicas: 2
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      name: aws-sub1
